"""add organisation_files models

Revision ID: 961c755a65e2
Revises: 
Create Date: 2023-10-29 10:44:10.568474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961c755a65e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=True)
    op.create_table('organisation_files',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organisation_id', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'file_name', name='org_file_name_uc')
    )
    op.create_index(op.f('ix_organisation_files_id'), 'organisation_files', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisation_files_id'), table_name='organisation_files')
    op.drop_table('organisation_files')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
